spring: 
    task: 
        jdbc: 
            initialize-schema: never # always/never
    cloud: 
        dataflow: 
            task: 
                initialize-enabled: false
                table-prefix: TASK_
                platform:
                    local:
                        accounts:
                            default:
                                workingDirectoriesRoot: ${user.home}/dataflow/tasks				
            applicationProperties:
                task:
                    globalProperties:
                        spring.datasource.url: jdbc:mysql://localhost:3306/sampleDB?useSSL=false&serverTimezone=UTC
                        spring.datasource.username: sampleuser
                        spring.datasource.password: sampleuser
                        spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
    datasource:
        url: jdbc:mysql://localhost:3306/sampleDB?useSSL=false&serverTimezone=UTC
        username: sampleuser
        password: sampleuser
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQL57Dialect  # 추가
        hibernate:
            ddl-auto: none
        show-sql: true
        properties: 
            hibernate: 
                dialect: org.hibernate.dialect.MySQL57Dialect			
    flyway: 
        enabled: false  # H2용 Flyway 비활성화	
    batch:
        jdbc:
            initialize-schema: never # always/never
            table-prefix: BATCH_
server:
    port: 9393
management:
    endpoints:
        web:
            exposure:
                include: health,info,prometheus
spring.cloud.dataflow.features.skipper-enabled: true
