server: 
    port: 6080
    connection-timeout: 10s
    tomcat: 
        accept-count: 100
        max-connections: 10000
        max-threads: 200
        min-spare-threads: 10
        max-swallow-size: 2MB
    error: 
        whitelabel: 
            enabled: true
    servlet: 
        context-path: /lightadmin
        jsp: 
            init-parameters: 
                development: true
        encoding: 
            force-response: true
            charset: UTF-8
    ssl: 
        enabled: false
        protocol: TLS
        enabled-protocols: 
            - TLSv1
            - TLSv1.1
            - TLSv1.2
        key-store: ${APP_HOME}/framework/dstone-batch-server/ssl/dstone-keystore.p12
        key-store-type: PKCS12
        key-store-password: ENC(vZbjr2NF87hEmiRHka9fUVIay5zvZeNtIRlNGHxvid8=)
        key-store-alias: dstone-ssl

spring: 
    main: 
        allow-bean-definition-overriding: true
    datasource: 
        name: dstone-batch-server-internal-db
        url: jdbc:mysql://localhost:3306/sampleDB
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ENC(tGnzOrm3eG/HcfRqgFO+VjbZ/2ZHQsR0Pt1hn8wpEXo=)
        password: ENC(bA7pEFbRRsL1NT+y9DZyq9z6+R6JqarooxqCr/DxG0w=)
    # 스프링배치        
    batch:
        lightmin:
            batch:
                repository-type: jdbc
                table-prefix: "BATCH_"
            repository:
                jdbc:
                    job-configuration-table-name: "BATCH_JOB_CONFIGURATION"
                    job-configuration-value-table-name: "BATCH_JOB_CONFIGURATION_VALUE"
                    job-configuration-parameter-table-name: "BATCH_JOB_CONFIGURATION_PARAMETERS"
            server:
                scheduler:
                    enabled: true
                    poller-period-retry: 86400000 # 클라이언트의 상태(health)를 주기적으로 확인하는 간격 (단위: 밀리초, 현재: 하루=86400000ms)
                    poller-period: 86400000 # 클라이언트 상태 확인에 실패했을 경우 재시도 간격 (단위: 밀리초, 현재: 하루=86400000ms)
                    repository:
                        delete-finished: true
                        keep-finished: PT24H
                        delete-lost: true
                        jdbc:
                            configuration-table: BATCH_SCHEDULER_CONFIGURATION
                            database-schema: FRAMEQ
                            configuration-value-table: BATCH_SCHEDULER_CONFIGURATION_VALUE
                            datasource-name: dataSource
                            execution-table: BATCH_SCHEDULER_EXECUTION