spring:
    cloud:
    skipper:
        server: 
        platform: 
            local: 
            accounts: 
                default: 
                workingDirectoriesRoot: ${user.home}/skipper/deployments
    datasource:
    url: jdbc:mysql://localhost:3306/sampleDB?useSSL=false&serverTimezone=UTC
    username: sampleuser
    password: sampleuser
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
server:
    port: 7577
logging: 
    level: 
    org.springframework.cloud.skipper: INFO
    