-- ============================================
-- DROP Spring Cloud Data Flow 2.11.5 Tables
-- ============================================

DROP TABLE IF EXISTS SCHEMA_VERSION;
DROP TABLE IF EXISTS TASK_EXECUTION_METADATA_SEQ;
DROP TABLE IF EXISTS TASK_EXECUTION_METADATA;
DROP TABLE IF EXISTS TASK_DEPLOYMENT;
DROP TABLE IF EXISTS TASK_DEFINITIONS;
DROP TABLE IF EXISTS STREAM_DEFINITIONS;
DROP TABLE IF EXISTS AUDIT_RECORDS;
DROP TABLE IF EXISTS APP_REGISTRATION;
DROP TABLE IF EXISTS HIBERNATE_SEQUENCE;

-- ============================================
-- DROP Spring Cloud Task 3.1.1 Tables
-- ============================================

DROP TABLE IF EXISTS TASK_LOCK;
DROP TABLE IF EXISTS TASK_SEQ;
DROP TABLE IF EXISTS TASK_TASK_BATCH;
DROP TABLE IF EXISTS TASK_EXECUTION_PARAMS;
DROP TABLE IF EXISTS TASK_EXECUTION;

-- ============================================
-- DROP Spring Batch 5.1.0 Tables
-- ============================================

DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_CONTEXT;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_CONTEXT;
DROP TABLE IF EXISTS BATCH_STEP_EXECUTION;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_PARAMS;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION;
DROP TABLE IF EXISTS BATCH_JOB_INSTANCE;
DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_SEQ;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_SEQ;
DROP TABLE IF EXISTS BATCH_JOB_SEQ;